// Web app config for online play (js/net.js), auto-generated by publish.sh —
// do not hand-edit. This is NOT a secret: this is the public config every
// Firebase web app ships to every visitor's browser, the same category of
// information as .firebaserc's project id, not a credential. See DEPLOY.md.
//
// Left null until publish.sh has run once against a project with Realtime
// Database enabled. Online play simply does not appear in the menu until then
// — everything else about the game is unaffected.
window.__FIREBASE_CONFIG = null;
